spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.31.133
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka , http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

zuul:
  routes:
    item-service: /item-service/**
    order-service: /order-service/**
    user-service: /user-service/**
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
